foreground            #e4e2e3
background            #131314
selection_foreground  #29313c
selection_background  #bfc7d5
url_color             #bbc7db
cursor                #bfc7d5
cursor_text_color     #29313c

color0   #131314
color1   #ffb4ab
color2   #bfc7d5
color3   #bbc7db
color4   #bfc7d5
color5   #bbc7db
color6   #3c4858
color7   #e4e2e3

color8   #919092
color9   #ffb4ab
color10  #bfc7d5
color11  #bbc7db
color12  #bfc7d5
color13  #bbc7db
color14  #3c4858
color15  #e4e2e3

tab_bar_background              #131314
tab_bar_margin_color            #131314
active_tab_foreground           #29313c
active_tab_background           #bfc7d5
inactive_tab_foreground         #c8c6c7
inactive_tab_background         #131314
